[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/api/webhook"
  function = "webhook"

[[edge_functions]]
  path = "/transaction"
  function = "transaction"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[headers]
  for = "/transaction"
    [headers.values]
    Cache-Control = "no-store, must-revalidate"
    X-Robots-Tag = "noindex"